# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"Crypto Oracle ratified isolate for Encrypted Zone"

module(
    name = "encrypted-zone-crypto-oracle",
    version = "0.0.0",
)

bazel_dep(name = "aspect_bazel_lib", version = "2.21.2")
bazel_dep(name = "protobuf", version = "33.4", repo_name = "com_google_protobuf")
bazel_dep(name = "rules_buf", version = "0.5.2")
bazel_dep(name = "rules_oci", version = "2.2.7")
bazel_dep(name = "rules_pkg", version = "1.2.0")
bazel_dep(name = "rules_python", version = "1.9.0")
bazel_dep(name = "rules_rust", version = "0.63.0")
bazel_dep(name = "rules_rust_prost", version = "0.63.0")
bazel_dep(name = "toolchains_llvm_bootstrapped", version = "0.2.4")
bazel_dep(name = "boringssl", version = "0.20260413.0")
bazel_dep(name = "sdk-patches", version = "0.0.0")
local_path_override(
    module_name = "sdk-patches",
    path = "../sdk/patches",
)

# SDK from submodule
bazel_dep(name = "privacy-sandbox-ez-sdk", version = "0.0.0")
local_path_override(
    module_name = "privacy-sandbox-ez-sdk",
    path = "../sdk",
)

# Configure hermetic C++ toolchain
register_toolchains(
    "@toolchains_llvm_bootstrapped//toolchain:linux_amd64",
)

# Configure Rust toolchain
rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = ["1.87.0"],
)
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")

# Custom Prost toolchain
register_toolchains(
    "@//toolchains:prost_toolchain",
)

# Create a repo for all crates used by Cargo-enabled targets, under "crates"
crate = use_extension(
    "@rules_rust//crate_universe:extension.bzl",
    "crate",
)
crate.spec(
    features = ["derive"],
    package = "clap",
    version = "4.5.53",
)
crate.spec(
    package = "tink-core",
    version = "0.3.0",
)
crate.spec(
    package = "tink-proto",
    version = "0.3.0",
)
crate.spec(
    package = "tink-signature",
    version = "0.3.0",
)
crate.spec(
    package = "debug-ignore",
    version = "1.0.5",
)
crate.spec(
    package = "tempfile",
    version = "3.13.0",
)
crate.from_specs(name = "oracle_crates")
use_repo(crate, "crates", "oracle_crates")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    ignore_root_user_error = True,
    python_version = "3.13",
)

pip2 = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip2.parse(
    hub_name = "sdk-pypi",
    python_version = "3.13",
    requirements_lock = "@privacy-sandbox-ez-sdk//tools/plugin:requirements_lock.txt",
)
use_repo(pip2, "sdk-pypi")

single_version_override(
    module_name = "grpc",
    patches = ["//:grpc_python_versions.patch"],
    version = "1.78.0",
)
